const allReviews = [
  {
    reviewOwnerName: 'Diego',
    reviewOwnerCountry: 'Greece',
    reviewData: 'Everything was perfect, from cleanliness to amenities.',
    reviewDate: '27/09/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/81.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Fatima',
    reviewOwnerCountry: 'Ireland',
    reviewData:
      'A wonderful experience, beautiful decor, and comfortable beds.',
    reviewDate: '17/02/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/23.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Diego',
    reviewOwnerCountry: 'Japan',
    reviewData: 'Excellent service and perfect location. Will visit again!',
    reviewDate: '23/02/2025',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/73.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Tatiana',
    reviewOwnerCountry: 'Turkey',
    reviewData: 'Very professional staff and high standards of hygiene.',
    reviewDate: '03/12/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/37.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Marc',
    reviewOwnerCountry: 'Thailand',
    reviewData: 'Excellent service and perfect location. Will visit again!',
    reviewDate: '07/12/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/90.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Sophia',
    reviewOwnerCountry: 'Sweden',
    reviewData:
      'A wonderful experience, beautiful decor, and comfortable beds.',
    reviewDate: '08/11/2022',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/46.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Carlos',
    reviewOwnerCountry: 'New Zealand',
    reviewData: 'Cozy rooms and very helpful staff.',
    reviewDate: '15/01/2025',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/44.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Anna',
    reviewOwnerCountry: 'Saudi Arabia',
    reviewData: 'Very professional staff and high standards of hygiene.',
    reviewDate: '14/12/2022',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/48.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Taro',
    reviewOwnerCountry: 'Turkey',
    reviewData: 'Cozy rooms and very helpful staff.',
    reviewDate: '31/08/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/15.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Chen',
    reviewOwnerCountry: 'Singapore',
    reviewData: 'Friendly host, great atmosphere, and very comfortable stay.',
    reviewDate: '20/11/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/44.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Ben',
    reviewOwnerCountry: 'Malaysia',
    reviewData: 'Very professional staff and high standards of hygiene.',
    reviewDate: '25/05/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/29.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Maria',
    reviewOwnerCountry: 'Thailand',
    reviewData:
      'Lovely place, very quiet and peaceful. Perfect for relaxation.',
    reviewDate: '31/03/2025',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/88.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Mohammed',
    reviewOwnerCountry: 'Netherlands',
    reviewData: 'A truly luxurious experience, with breathtaking views.',
    reviewDate: '30/10/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/9.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Linda',
    reviewOwnerCountry: 'France',
    reviewData: 'Great place, clean, and a friendly atmosphere!',
    reviewDate: '12/01/2025',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/27.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Diego',
    reviewOwnerCountry: 'USA',
    reviewData: 'The best customer service I have experienced.',
    reviewDate: '04/11/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/84.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Monica',
    reviewOwnerCountry: 'Brazil',
    reviewData: 'A truly luxurious experience, with breathtaking views.',
    reviewDate: '15/08/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/42.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Ben',
    reviewOwnerCountry: 'Vietnam',
    reviewData: 'Very professional staff and high standards of hygiene.',
    reviewDate: '06/10/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/28.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Chen',
    reviewOwnerCountry: 'Ukraine',
    reviewData: 'Cozy rooms and very helpful staff.',
    reviewDate: '02/08/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/92.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Hassan',
    reviewOwnerCountry: 'Australia',
    reviewData: 'Excellent service and perfect location. Will visit again!',
    reviewDate: '07/09/2022',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/26.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Sophie',
    reviewOwnerCountry: 'France',
    reviewData: 'Super comfortable and well-located.',
    reviewDate: '02/05/2022',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/74.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Leo',
    reviewOwnerCountry: 'Denmark',
    reviewData: 'Everything was perfect, from cleanliness to amenities.',
    reviewDate: '27/05/2022',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/2.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Emma',
    reviewOwnerCountry: 'United Kingdom',
    reviewData: 'Very professional staff and high standards of hygiene.',
    reviewDate: '18/06/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/97.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Gabriel',
    reviewOwnerCountry: 'Ukraine',
    reviewData: 'The best customer service I have experienced.',
    reviewDate: '18/05/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/60.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Isabella',
    reviewOwnerCountry: 'Germany',
    reviewData: 'Very professional staff and high standards of hygiene.',
    reviewDate: '12/03/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/5.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Ken',
    reviewOwnerCountry: 'Saudi Arabia',
    reviewData: 'Friendly host, great atmosphere, and very comfortable stay.',
    reviewDate: '15/05/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/98.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Isabella',
    reviewOwnerCountry: 'USA',
    reviewData:
      'Lovely place, very quiet and peaceful. Perfect for relaxation.',
    reviewDate: '08/09/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/19.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'John',
    reviewOwnerCountry: 'Sweden',
    reviewData: 'The best customer service I have experienced.',
    reviewDate: '11/08/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/18.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Tatiana',
    reviewOwnerCountry: 'Malaysia',
    reviewData: 'Super comfortable and well-located.',
    reviewDate: '03/06/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/71.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Ben',
    reviewOwnerCountry: 'South Korea',
    reviewData: 'Very professional staff and high standards of hygiene.',
    reviewDate: '26/05/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/93.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Monica',
    reviewOwnerCountry: 'Czech Republic',
    reviewData:
      'Lovely place, very quiet and peaceful. Perfect for relaxation.',
    reviewDate: '05/11/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/29.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Hassan',
    reviewOwnerCountry: 'India',
    reviewData: 'Friendly host, great atmosphere, and very comfortable stay.',
    reviewDate: '21/07/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/79.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Nina',
    reviewOwnerCountry: 'Finland',
    reviewData: 'Everything was perfect, from cleanliness to amenities.',
    reviewDate: '18/08/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/39.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Daniel',
    reviewOwnerCountry: 'Chile',
    reviewData: 'Friendly host, great atmosphere, and very comfortable stay.',
    reviewDate: '17/12/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/92.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Nina',
    reviewOwnerCountry: 'Spain',
    reviewData: 'Super comfortable and well-located.',
    reviewDate: '18/12/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/31.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Andrei',
    reviewOwnerCountry: 'Malaysia',
    reviewData: 'Excellent service and perfect location. Will visit again!',
    reviewDate: '08/02/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/41.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Linda',
    reviewOwnerCountry: 'Mexico',
    reviewData: 'Super comfortable and well-located.',
    reviewDate: '14/06/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/34.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Diego',
    reviewOwnerCountry: 'Belgium',
    reviewData:
      'A wonderful experience, beautiful decor, and comfortable beds.',
    reviewDate: '19/11/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/27.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Linda',
    reviewOwnerCountry: 'South Korea',
    reviewData:
      'A wonderful experience, beautiful decor, and comfortable beds.',
    reviewDate: '10/06/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/82.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Ali',
    reviewOwnerCountry: 'Portugal',
    reviewData: 'Excellent service and perfect location. Will visit again!',
    reviewDate: '29/03/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/50.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Maria',
    reviewOwnerCountry: 'Netherlands',
    reviewData: 'Excellent service and perfect location. Will visit again!',
    reviewDate: '25/05/2022',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/75.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Taro',
    reviewOwnerCountry: 'Denmark',
    reviewData: 'A truly luxurious experience, with breathtaking views.',
    reviewDate: '25/12/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/34.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Chen',
    reviewOwnerCountry: 'Vietnam',
    reviewData: 'Excellent service and perfect location. Will visit again!',
    reviewDate: '24/07/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/55.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Oscar',
    reviewOwnerCountry: 'India',
    reviewData:
      'Lovely place, very quiet and peaceful. Perfect for relaxation.',
    reviewDate: '03/04/2022',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/4.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Maria',
    reviewOwnerCountry: 'China',
    reviewData:
      'Lovely place, very quiet and peaceful. Perfect for relaxation.',
    reviewDate: '14/11/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/98.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Taro',
    reviewOwnerCountry: 'Netherlands',
    reviewData:
      'Lovely place, very quiet and peaceful. Perfect for relaxation.',
    reviewDate: '01/10/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/70.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Zoe',
    reviewOwnerCountry: 'Vietnam',
    reviewData: 'Cozy rooms and very helpful staff.',
    reviewDate: '29/07/2022',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/7.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'John',
    reviewOwnerCountry: 'Greece',
    reviewData: 'Cozy rooms and very helpful staff.',
    reviewDate: '26/01/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/51.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Sophia',
    reviewOwnerCountry: 'Germany',
    reviewData: 'The best customer service I have experienced.',
    reviewDate: '20/09/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/25.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Leo',
    reviewOwnerCountry: 'United Kingdom',
    reviewData:
      'A wonderful experience, beautiful decor, and comfortable beds.',
    reviewDate: '27/08/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/21.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Laura',
    reviewOwnerCountry: 'Canada',
    reviewData: 'Cozy rooms and very helpful staff.',
    reviewDate: '28/11/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/56.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Leo',
    reviewOwnerCountry: 'New Zealand',
    reviewData: 'Very professional staff and high standards of hygiene.',
    reviewDate: '27/03/2025',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/82.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Jasmine',
    reviewOwnerCountry: 'Thailand',
    reviewData: 'Great place, clean, and a friendly atmosphere!',
    reviewDate: '22/09/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/77.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'John',
    reviewOwnerCountry: 'Germany',
    reviewData: 'Excellent service and perfect location. Will visit again!',
    reviewDate: '17/02/2022',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/54.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Tatiana',
    reviewOwnerCountry: 'United Kingdom',
    reviewData: 'The best customer service I have experienced.',
    reviewDate: '25/05/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/68.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'James',
    reviewOwnerCountry: 'India',
    reviewData: 'The best customer service I have experienced.',
    reviewDate: '08/04/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/95.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Olga',
    reviewOwnerCountry: 'Turkey',
    reviewData: 'Cozy rooms and very helpful staff.',
    reviewDate: '19/01/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/81.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'John',
    reviewOwnerCountry: 'Czech Republic',
    reviewData: 'A truly luxurious experience, with breathtaking views.',
    reviewDate: '18/06/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/58.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Jasmine',
    reviewOwnerCountry: 'Malaysia',
    reviewData: 'Excellent service and perfect location. Will visit again!',
    reviewDate: '17/04/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/63.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Marc',
    reviewOwnerCountry: 'Ireland',
    reviewData: 'Great place, clean, and a friendly atmosphere!',
    reviewDate: '14/06/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/77.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Aliya',
    reviewOwnerCountry: 'New Zealand',
    reviewData: 'A truly luxurious experience, with breathtaking views.',
    reviewDate: '29/01/2022',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/20.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Chen',
    reviewOwnerCountry: 'Denmark',
    reviewData: 'A truly luxurious experience, with breathtaking views.',
    reviewDate: '07/10/2022',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/39.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Anna',
    reviewOwnerCountry: 'United Kingdom',
    reviewData: 'Great place, clean, and a friendly atmosphere!',
    reviewDate: '11/01/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/51.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Ben',
    reviewOwnerCountry: 'Chile',
    reviewData: 'Very professional staff and high standards of hygiene.',
    reviewDate: '08/10/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/12.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Isabella',
    reviewOwnerCountry: 'Australia',
    reviewData: 'Very professional staff and high standards of hygiene.',
    reviewDate: '07/08/2022',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/95.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'James',
    reviewOwnerCountry: 'Norway',
    reviewData: 'Great place, clean, and a friendly atmosphere!',
    reviewDate: '30/12/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/43.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Nina',
    reviewOwnerCountry: 'Poland',
    reviewData: 'A truly luxurious experience, with breathtaking views.',
    reviewDate: '19/02/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/69.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'James',
    reviewOwnerCountry: 'Poland',
    reviewData:
      'Lovely place, very quiet and peaceful. Perfect for relaxation.',
    reviewDate: '23/07/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/10.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Anna',
    reviewOwnerCountry: 'South Africa',
    reviewData:
      'A wonderful experience, beautiful decor, and comfortable beds.',
    reviewDate: '15/03/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/43.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Dmitry',
    reviewOwnerCountry: 'Indonesia',
    reviewData: 'A truly luxurious experience, with breathtaking views.',
    reviewDate: '25/03/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/85.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Sophie',
    reviewOwnerCountry: 'Argentina',
    reviewData: 'A truly luxurious experience, with breathtaking views.',
    reviewDate: '23/11/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/22.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Taro',
    reviewOwnerCountry: 'Finland',
    reviewData:
      'A wonderful experience, beautiful decor, and comfortable beds.',
    reviewDate: '06/02/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/40.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Tatiana',
    reviewOwnerCountry: 'Netherlands',
    reviewData: 'Excellent service and perfect location. Will visit again!',
    reviewDate: '26/07/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/61.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Ben',
    reviewOwnerCountry: 'Portugal',
    reviewData: 'Cozy rooms and very helpful staff.',
    reviewDate: '04/09/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/3.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Anna',
    reviewOwnerCountry: 'Malaysia',
    reviewData: 'A truly luxurious experience, with breathtaking views.',
    reviewDate: '27/03/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/45.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'John',
    reviewOwnerCountry: 'Ireland',
    reviewData: 'Great place, clean, and a friendly atmosphere!',
    reviewDate: '15/07/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/11.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Linda',
    reviewOwnerCountry: 'Vietnam',
    reviewData: 'Cozy rooms and very helpful staff.',
    reviewDate: '27/12/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/14.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Ali',
    reviewOwnerCountry: 'Sweden',
    reviewData:
      'Lovely place, very quiet and peaceful. Perfect for relaxation.',
    reviewDate: '01/01/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/87.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Zoe',
    reviewOwnerCountry: 'Denmark',
    reviewData: 'A truly luxurious experience, with breathtaking views.',
    reviewDate: '25/07/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/47.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Taro',
    reviewOwnerCountry: 'Ukraine',
    reviewData: 'Everything was perfect, from cleanliness to amenities.',
    reviewDate: '20/07/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/65.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Fatima',
    reviewOwnerCountry: 'Finland',
    reviewData: 'A truly luxurious experience, with breathtaking views.',
    reviewDate: '20/06/2022',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/66.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Marc',
    reviewOwnerCountry: 'Argentina',
    reviewData: 'Friendly host, great atmosphere, and very comfortable stay.',
    reviewDate: '04/10/2022',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/49.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Zoe',
    reviewOwnerCountry: 'Mexico',
    reviewData: 'Excellent service and perfect location. Will visit again!',
    reviewDate: '29/08/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/49.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Carlos',
    reviewOwnerCountry: 'South Korea',
    reviewData: 'Cozy rooms and very helpful staff.',
    reviewDate: '20/11/2022',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/23.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Isabella',
    reviewOwnerCountry: 'Finland',
    reviewData: 'Everything was perfect, from cleanliness to amenities.',
    reviewDate: '21/10/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/18.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Chen',
    reviewOwnerCountry: 'USA',
    reviewData:
      'Lovely place, very quiet and peaceful. Perfect for relaxation.',
    reviewDate: '25/02/2022',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/88.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Vera',
    reviewOwnerCountry: 'Poland',
    reviewData: 'Cozy rooms and very helpful staff.',
    reviewDate: '07/07/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/87.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Daniel',
    reviewOwnerCountry: 'South Africa',
    reviewData: 'Very professional staff and high standards of hygiene.',
    reviewDate: '05/08/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/91.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Jasmine',
    reviewOwnerCountry: 'Czech Republic',
    reviewData: 'Friendly host, great atmosphere, and very comfortable stay.',
    reviewDate: '04/11/2022',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/99.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Carlos',
    reviewOwnerCountry: 'Sweden',
    reviewData:
      'Lovely place, very quiet and peaceful. Perfect for relaxation.',
    reviewDate: '30/06/2022',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/89.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Fatima',
    reviewOwnerCountry: 'Brazil',
    reviewData: 'Cozy rooms and very helpful staff.',
    reviewDate: '16/07/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/10.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Diego',
    reviewOwnerCountry: 'Greece',
    reviewData:
      'Lovely place, very quiet and peaceful. Perfect for relaxation.',
    reviewDate: '30/11/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/47.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Emma',
    reviewOwnerCountry: 'South Korea',
    reviewData: 'Excellent service and perfect location. Will visit again!',
    reviewDate: '18/01/2022',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/36.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Ben',
    reviewOwnerCountry: 'Denmark',
    reviewData: 'Super comfortable and well-located.',
    reviewDate: '21/04/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/1.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Aliya',
    reviewOwnerCountry: 'Sweden',
    reviewData:
      'Lovely place, very quiet and peaceful. Perfect for relaxation.',
    reviewDate: '07/03/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/94.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Chen',
    reviewOwnerCountry: 'United Arab Emirates',
    reviewData: 'Cozy rooms and very helpful staff.',
    reviewDate: '02/04/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/31.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Emma',
    reviewOwnerCountry: 'Greece',
    reviewData:
      'A wonderful experience, beautiful decor, and comfortable beds.',
    reviewDate: '31/05/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/89.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Marc',
    reviewOwnerCountry: 'New Zealand',
    reviewData: 'A truly luxurious experience, with breathtaking views.',
    reviewDate: '11/03/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/16.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Jasmine',
    reviewOwnerCountry: 'India',
    reviewData: 'Super comfortable and well-located.',
    reviewDate: '25/12/2022',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/65.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Carlos',
    reviewOwnerCountry: 'Indonesia',
    reviewData:
      'Lovely place, very quiet and peaceful. Perfect for relaxation.',
    reviewDate: '09/06/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/42.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Sophie',
    reviewOwnerCountry: 'South Korea',
    reviewData: 'Everything was perfect, from cleanliness to amenities.',
    reviewDate: '07/08/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/11.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Ben',
    reviewOwnerCountry: 'Ukraine',
    reviewData: 'Super comfortable and well-located.',
    reviewDate: '11/02/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/64.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Olga',
    reviewOwnerCountry: 'South Africa',
    reviewData: 'Friendly host, great atmosphere, and very comfortable stay.',
    reviewDate: '12/10/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/78.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Tom',
    reviewOwnerCountry: 'Brazil',
    reviewData: 'The best customer service I have experienced.',
    reviewDate: '14/06/2022',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/46.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Zoe',
    reviewOwnerCountry: 'Singapore',
    reviewData: 'Friendly host, great atmosphere, and very comfortable stay.',
    reviewDate: '12/07/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/60.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Ben',
    reviewOwnerCountry: 'Indonesia',
    reviewData: 'Cozy rooms and very helpful staff.',
    reviewDate: '21/09/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/13.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Fatima',
    reviewOwnerCountry: 'Spain',
    reviewData: 'The best customer service I have experienced.',
    reviewDate: '13/04/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/79.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'James',
    reviewOwnerCountry: 'Netherlands',
    reviewData: 'The best customer service I have experienced.',
    reviewDate: '11/03/2022',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/99.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Zoe',
    reviewOwnerCountry: 'Brazil',
    reviewData: 'Excellent service and perfect location. Will visit again!',
    reviewDate: '22/02/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/72.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Mohammed',
    reviewOwnerCountry: 'Greece',
    reviewData: 'Very professional staff and high standards of hygiene.',
    reviewDate: '26/08/2022',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/67.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Emma',
    reviewOwnerCountry: 'Indonesia',
    reviewData: 'Excellent service and perfect location. Will visit again!',
    reviewDate: '13/11/2022',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/90.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Hassan',
    reviewOwnerCountry: 'Norway',
    reviewData:
      'A wonderful experience, beautiful decor, and comfortable beds.',
    reviewDate: '01/01/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/6.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Emma',
    reviewOwnerCountry: 'Japan',
    reviewData:
      'A wonderful experience, beautiful decor, and comfortable beds.',
    reviewDate: '21/12/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/91.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Diego',
    reviewOwnerCountry: 'South Korea',
    reviewData: 'Super comfortable and well-located.',
    reviewDate: '26/12/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/20.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Sophia',
    reviewOwnerCountry: 'South Africa',
    reviewData: 'Super comfortable and well-located.',
    reviewDate: '07/12/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/16.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Oscar',
    reviewOwnerCountry: 'Germany',
    reviewData: 'Cozy rooms and very helpful staff.',
    reviewDate: '09/06/2022',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/55.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Yana',
    reviewOwnerCountry: 'Norway',
    reviewData: 'Friendly host, great atmosphere, and very comfortable stay.',
    reviewDate: '11/10/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/64.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Leo',
    reviewOwnerCountry: 'Indonesia',
    reviewData: 'Excellent service and perfect location. Will visit again!',
    reviewDate: '24/08/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/86.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Sophia',
    reviewOwnerCountry: 'New Zealand',
    reviewData: 'Friendly host, great atmosphere, and very comfortable stay.',
    reviewDate: '08/09/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/93.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Andrei',
    reviewOwnerCountry: 'Netherlands',
    reviewData: 'Cozy rooms and very helpful staff.',
    reviewDate: '05/07/2022',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/94.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Laura',
    reviewOwnerCountry: 'Saudi Arabia',
    reviewData: 'Everything was perfect, from cleanliness to amenities.',
    reviewDate: '20/07/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/80.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Gabriel',
    reviewOwnerCountry: 'Sweden',
    reviewData: 'Friendly host, great atmosphere, and very comfortable stay.',
    reviewDate: '30/04/2022',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/68.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Aliya',
    reviewOwnerCountry: 'Denmark',
    reviewData: 'Very professional staff and high standards of hygiene.',
    reviewDate: '02/04/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/70.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Tom',
    reviewOwnerCountry: 'Denmark',
    reviewData: 'The best customer service I have experienced.',
    reviewDate: '09/12/2022',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/76.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Monica',
    reviewOwnerCountry: 'Ireland',
    reviewData: 'Everything was perfect, from cleanliness to amenities.',
    reviewDate: '01/07/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/6.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Tom',
    reviewOwnerCountry: 'Italy',
    reviewData:
      'A wonderful experience, beautiful decor, and comfortable beds.',
    reviewDate: '08/02/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/52.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Vera',
    reviewOwnerCountry: 'Singapore',
    reviewData: 'Excellent service and perfect location. Will visit again!',
    reviewDate: '05/10/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/2.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Marc',
    reviewOwnerCountry: 'Switzerland',
    reviewData: 'Cozy rooms and very helpful staff.',
    reviewDate: '09/06/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/61.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Nina',
    reviewOwnerCountry: 'New Zealand',
    reviewData: 'Super comfortable and well-located.',
    reviewDate: '26/03/2022',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/83.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Ken',
    reviewOwnerCountry: 'Belgium',
    reviewData: 'Great place, clean, and a friendly atmosphere!',
    reviewDate: '21/01/2025',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/66.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Maria',
    reviewOwnerCountry: 'Italy',
    reviewData: 'Everything was perfect, from cleanliness to amenities.',
    reviewDate: '04/11/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/8.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Taro',
    reviewOwnerCountry: 'Czech Republic',
    reviewData: 'Everything was perfect, from cleanliness to amenities.',
    reviewDate: '22/03/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/33.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Aliya',
    reviewOwnerCountry: 'Poland',
    reviewData: 'Everything was perfect, from cleanliness to amenities.',
    reviewDate: '27/03/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/53.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Tom',
    reviewOwnerCountry: 'Argentina',
    reviewData: 'Everything was perfect, from cleanliness to amenities.',
    reviewDate: '19/07/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/74.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Isabella',
    reviewOwnerCountry: 'Ukraine',
    reviewData: 'Super comfortable and well-located.',
    reviewDate: '02/04/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/96.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Andrei',
    reviewOwnerCountry: 'Netherlands',
    reviewData: 'Great place, clean, and a friendly atmosphere!',
    reviewDate: '18/02/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/38.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Sophie',
    reviewOwnerCountry: 'Denmark',
    reviewData:
      'Lovely place, very quiet and peaceful. Perfect for relaxation.',
    reviewDate: '07/10/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/41.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Taro',
    reviewOwnerCountry: 'Thailand',
    reviewData: 'Everything was perfect, from cleanliness to amenities.',
    reviewDate: '18/06/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/53.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Monica',
    reviewOwnerCountry: 'Turkey',
    reviewData: 'Excellent service and perfect location. Will visit again!',
    reviewDate: '10/03/2025',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/76.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Taro',
    reviewOwnerCountry: 'Italy',
    reviewData: 'Very professional staff and high standards of hygiene.',
    reviewDate: '22/12/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/63.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Fatima',
    reviewOwnerCountry: 'Switzerland',
    reviewData: 'Great place, clean, and a friendly atmosphere!',
    reviewDate: '22/08/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/86.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'James',
    reviewOwnerCountry: 'Germany',
    reviewData:
      'A wonderful experience, beautiful decor, and comfortable beds.',
    reviewDate: '16/03/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/45.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Vera',
    reviewOwnerCountry: 'Poland',
    reviewData: 'A truly luxurious experience, with breathtaking views.',
    reviewDate: '09/03/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/85.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Hassan',
    reviewOwnerCountry: 'Norway',
    reviewData: 'Super comfortable and well-located.',
    reviewDate: '14/10/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/71.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Olga',
    reviewOwnerCountry: 'Denmark',
    reviewData: 'Cozy rooms and very helpful staff.',
    reviewDate: '02/07/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/1.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Carlos',
    reviewOwnerCountry: 'Czech Republic',
    reviewData: 'Friendly host, great atmosphere, and very comfortable stay.',
    reviewDate: '13/07/2022',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/22.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Yana',
    reviewOwnerCountry: 'Ireland',
    reviewData: 'The best customer service I have experienced.',
    reviewDate: '20/04/2022',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/67.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Leo',
    reviewOwnerCountry: 'Czech Republic',
    reviewData: 'Super comfortable and well-located.',
    reviewDate: '13/04/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/19.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Aliya',
    reviewOwnerCountry: 'Brazil',
    reviewData: 'Great place, clean, and a friendly atmosphere!',
    reviewDate: '22/07/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/17.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Ali',
    reviewOwnerCountry: 'Netherlands',
    reviewData:
      'Lovely place, very quiet and peaceful. Perfect for relaxation.',
    reviewDate: '10/12/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/35.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Jasmine',
    reviewOwnerCountry: 'Indonesia',
    reviewData: 'Friendly host, great atmosphere, and very comfortable stay.',
    reviewDate: '09/01/2022',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/13.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Andrei',
    reviewOwnerCountry: 'Switzerland',
    reviewData: 'A truly luxurious experience, with breathtaking views.',
    reviewDate: '08/02/2022',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/36.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Linda',
    reviewOwnerCountry: 'Denmark',
    reviewData: 'Cozy rooms and very helpful staff.',
    reviewDate: '13/03/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/35.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'James',
    reviewOwnerCountry: 'South Africa',
    reviewData: 'Cozy rooms and very helpful staff.',
    reviewDate: '17/03/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/25.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Vera',
    reviewOwnerCountry: 'Switzerland',
    reviewData: 'Super comfortable and well-located.',
    reviewDate: '29/11/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/62.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Carlos',
    reviewOwnerCountry: 'Portugal',
    reviewData: 'Cozy rooms and very helpful staff.',
    reviewDate: '13/08/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/32.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Fatima',
    reviewOwnerCountry: 'Argentina',
    reviewData: 'Friendly host, great atmosphere, and very comfortable stay.',
    reviewDate: '29/01/2025',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/24.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Andrei',
    reviewOwnerCountry: 'Germany',
    reviewData:
      'Lovely place, very quiet and peaceful. Perfect for relaxation.',
    reviewDate: '25/10/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/72.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Isabella',
    reviewOwnerCountry: 'China',
    reviewData: 'Very professional staff and high standards of hygiene.',
    reviewDate: '12/03/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/9.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'John',
    reviewOwnerCountry: 'Thailand',
    reviewData: 'A truly luxurious experience, with breathtaking views.',
    reviewDate: '30/09/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/78.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Sophia',
    reviewOwnerCountry: 'Netherlands',
    reviewData: 'Cozy rooms and very helpful staff.',
    reviewDate: '27/01/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/59.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Carlos',
    reviewOwnerCountry: 'United Arab Emirates',
    reviewData: 'Excellent service and perfect location. Will visit again!',
    reviewDate: '13/11/2022',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/24.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Tatiana',
    reviewOwnerCountry: 'Turkey',
    reviewData: 'Great place, clean, and a friendly atmosphere!',
    reviewDate: '21/06/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/40.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Oscar',
    reviewOwnerCountry: 'United Arab Emirates',
    reviewData: 'The best customer service I have experienced.',
    reviewDate: '10/08/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/75.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Tatiana',
    reviewOwnerCountry: 'United Arab Emirates',
    reviewData: 'The best customer service I have experienced.',
    reviewDate: '18/01/2022',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/52.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Chen',
    reviewOwnerCountry: 'Greece',
    reviewData: 'The best customer service I have experienced.',
    reviewDate: '16/05/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/69.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Chen',
    reviewOwnerCountry: 'United Arab Emirates',
    reviewData: 'Excellent service and perfect location. Will visit again!',
    reviewDate: '18/04/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/15.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Dmitry',
    reviewOwnerCountry: 'Spain',
    reviewData: 'Friendly host, great atmosphere, and very comfortable stay.',
    reviewDate: '09/01/2022',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/14.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Sophia',
    reviewOwnerCountry: 'Finland',
    reviewData: 'A truly luxurious experience, with breathtaking views.',
    reviewDate: '06/01/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/3.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Mohammed',
    reviewOwnerCountry: 'Belgium',
    reviewData: 'Excellent service and perfect location. Will visit again!',
    reviewDate: '09/09/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/59.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Monica',
    reviewOwnerCountry: 'Belgium',
    reviewData: 'Friendly host, great atmosphere, and very comfortable stay.',
    reviewDate: '08/03/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/38.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Oscar',
    reviewOwnerCountry: 'United Kingdom',
    reviewData: 'Cozy rooms and very helpful staff.',
    reviewDate: '19/03/2022',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/96.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Aliya',
    reviewOwnerCountry: 'Germany',
    reviewData:
      'A wonderful experience, beautiful decor, and comfortable beds.',
    reviewDate: '06/11/2022',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/84.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'James',
    reviewOwnerCountry: 'Turkey',
    reviewData: 'Excellent service and perfect location. Will visit again!',
    reviewDate: '08/10/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/57.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Jasmine',
    reviewOwnerCountry: 'Italy',
    reviewData: 'Everything was perfect, from cleanliness to amenities.',
    reviewDate: '23/04/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/54.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Andrei',
    reviewOwnerCountry: 'Finland',
    reviewData: 'Everything was perfect, from cleanliness to amenities.',
    reviewDate: '06/12/2022',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/83.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Laura',
    reviewOwnerCountry: 'Austria',
    reviewData: 'Super comfortable and well-located.',
    reviewDate: '12/12/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/30.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Leo',
    reviewOwnerCountry: 'New Zealand',
    reviewData: 'Very professional staff and high standards of hygiene.',
    reviewDate: '30/01/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/17.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Aliya',
    reviewOwnerCountry: 'Norway',
    reviewData: 'Excellent service and perfect location. Will visit again!',
    reviewDate: '30/12/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/21.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Taro',
    reviewOwnerCountry: 'Denmark',
    reviewData: 'The best customer service I have experienced.',
    reviewDate: '01/01/2022',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/37.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Yana',
    reviewOwnerCountry: 'Thailand',
    reviewData:
      'Lovely place, very quiet and peaceful. Perfect for relaxation.',
    reviewDate: '06/07/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/57.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Dmitry',
    reviewOwnerCountry: 'Malaysia',
    reviewData:
      'Lovely place, very quiet and peaceful. Perfect for relaxation.',
    reviewDate: '25/10/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/80.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Nina',
    reviewOwnerCountry: 'United Arab Emirates',
    reviewData: 'Great place, clean, and a friendly atmosphere!',
    reviewDate: '17/06/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/32.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Gabriel',
    reviewOwnerCountry: 'South Korea',
    reviewData: 'A truly luxurious experience, with breathtaking views.',
    reviewDate: '21/11/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/97.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Chen',
    reviewOwnerCountry: 'Portugal',
    reviewData: 'Great place, clean, and a friendly atmosphere!',
    reviewDate: '11/07/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/50.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Dmitry',
    reviewOwnerCountry: 'Spain',
    reviewData: 'Everything was perfect, from cleanliness to amenities.',
    reviewDate: '23/05/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/8.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Vera',
    reviewOwnerCountry: 'Vietnam',
    reviewData: 'Everything was perfect, from cleanliness to amenities.',
    reviewDate: '30/10/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/33.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Diego',
    reviewOwnerCountry: 'Argentina',
    reviewData: 'Excellent service and perfect location. Will visit again!',
    reviewDate: '26/09/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/56.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Laura',
    reviewOwnerCountry: 'Czech Republic',
    reviewData: 'Friendly host, great atmosphere, and very comfortable stay.',
    reviewDate: '06/01/2025',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/73.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Andrei',
    reviewOwnerCountry: 'Italy',
    reviewData:
      'Lovely place, very quiet and peaceful. Perfect for relaxation.',
    reviewDate: '24/03/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/30.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Jasmine',
    reviewOwnerCountry: 'Germany',
    reviewData: 'Friendly host, great atmosphere, and very comfortable stay.',
    reviewDate: '09/10/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/28.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'John',
    reviewOwnerCountry: 'France',
    reviewData: 'Excellent service and perfect location. Will visit again!',
    reviewDate: '09/09/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/62.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Jasmine',
    reviewOwnerCountry: 'Switzerland',
    reviewData: 'Friendly host, great atmosphere, and very comfortable stay.',
    reviewDate: '18/10/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/12.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Taro',
    reviewOwnerCountry: 'Indonesia',
    reviewData: 'Cozy rooms and very helpful staff.',
    reviewDate: '20/10/2021',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/7.jpg',
    ranking: '5',
  },
  {
    reviewOwnerName: 'Isabella',
    reviewOwnerCountry: 'Portugal',
    reviewData: 'Great place, clean, and a friendly atmosphere!',
    reviewDate: '07/09/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/4.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Taro',
    reviewOwnerCountry: 'New Zealand',
    reviewData: 'Excellent service and perfect location. Will visit again!',
    reviewDate: '08/03/2025',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/5.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Olga',
    reviewOwnerCountry: 'Thailand',
    reviewData: 'Friendly host, great atmosphere, and very comfortable stay.',
    reviewDate: '22/03/2022',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/58.jpg',
    ranking: '4',
  },
  {
    reviewOwnerName: 'Ali',
    reviewOwnerCountry: 'France',
    reviewData: 'Very professional staff and high standards of hygiene.',
    reviewDate: '26/11/2023',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/men/48.jpg',
    ranking: '4.5',
  },
  {
    reviewOwnerName: 'Olga',
    reviewOwnerCountry: 'Poland',
    reviewData: 'Everything was perfect, from cleanliness to amenities.',
    reviewDate: '21/09/2024',
    reviewOwnerPhoto: 'https://randomuser.me/api/portraits/women/26.jpg',
    ranking: '4.5',
  },
]

module.exports = { allReviews }
